### ISSUE TITLE
Server down

### ISSUE THREAD

**Issue by hohyon-ryu** [gunjaag/twitter-korean-tokenizer-api#4]
Hi Gunja,

The server seems currently down. No hurries on fixing this. I just wanted to let you know.

Thank you so much as always. :)
- Will

**Comment by gunjaag** [comment]
Hi Will,

I had accidentally changed security group settings, I have fixed it - so it should be working fine. Also, the version upgrade totally slipped my mind after I returned back. I will work on that too. Sorry again for missing on that.

Gunja

**Comment by gunjaag** [comment]
Updated library version to 4.0 and changed UI to support phrase tokenization
